"""empty message

Revision ID: 52982554c1ac
Revises: 1eac68a8efff
Create Date: 2020-09-03 13:55:59.090462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52982554c1ac'
down_revision = '1eac68a8efff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
